import type { Express, Request, Response } from "express";
import { and, desc, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { getDb, getOwnedFarm } from "./db";
import { sdk } from "./_core/sdk";
import { getPublicAgricultureData, getWeather } from "./integrations/agriData";
import { alerts, advisories, cropAssessments, crops, farms, fields, farmerProfiles, nudges } from "../drizzle/schema";

const api = "/api/v1";
const unavailable = (provider: string) => ({ available: false, provider, reason: `${provider} is not configured; returning a safe fallback.` });

const memory = {
  profiles: new Map<string, any>(), farms: new Map<string, any>(), fields: new Map<string, any>(),
  advisories: new Map<string, any>(), assessments: new Map<string, any>(), alerts: new Map<string, any>(), nudges: new Map<string, any>(),
};

const farmerSchema = z.object({ name: z.string().min(2).max(120), phone: z.string().max(32).optional(), language: z.string().min(2).max(12).default("en"), country: z.string().length(2).default("IN") });
const farmSchema = z.object({ name: z.string().min(2).max(120), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), areaHectares: z.number().positive().max(100000) });
const fieldSchema = z.object({ farmId: z.string().min(1), name: z.string().min(1).max(120), crop: z.string().min(1).max(80), areaHectares: z.number().positive().max(100000).optional() });
const chatSchema = z.object({ message: z.string().min(1).max(4000), language: z.string().min(2).max(20).default("English"), farmId: z.string().optional(), crop: z.string().max(80).optional() });
const analysisSchema = z.object({ farmId: z.string().min(1), crop: z.string().min(1).max(80), includeSatellite: z.boolean().default(true), includeWeather: z.boolean().default(true), includeSoil: z.boolean().default(true) });
const photoSchema = z.object({ farmId: z.string().optional(), crop: z.string().min(1).max(80), imageUrl: z.string().url().optional(), imageBase64: z.string().max(8_000_000).optional(), mimeType: z.string().max(100).default("image/jpeg"), language: z.string().max(20).default("English") }).refine(v => Boolean(v.imageUrl || v.imageBase64), "imageUrl or imageBase64 is required");

async function auth(req: Request, res: Response) {
  try { return await sdk.authenticateRequest(req); } catch { res.status(401).json({ error: "Authentication required" }); return null; }
}
function id(prefix: string) { return `${prefix}_${nanoid(12)}`; }
function jsonError(res: Response, error: unknown) { res.status(400).json({ error: error instanceof Error ? error.message : "Invalid request" }); }

export async function gemini(prompt: string, image?: { data: string; mimeType: string }) {
  const key = process.env.GOOGLE_GEMINI_API_KEY;
  if (!key) return { ...unavailable("Google Gemini"), text: "AI guidance is temporarily unavailable. Please consult a local agricultural officer before taking treatment action." };
  const parts: any[] = [{ text: prompt }];
  if (image) parts.push({ inline_data: { mime_type: image.mimeType, data: image.data } });
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ role: "user", parts }], generationConfig: { temperature: 0.2, responseMimeType: "application/json" } }) });
  if (!response.ok) throw new Error(`Gemini request failed (${response.status})`);
  const body = await response.json() as any;
  const text = body?.candidates?.[0]?.content?.parts?.map((p: any) => p.text || "").join("") || "{}";
  try { return { available: true, provider: "Google Gemini", data: JSON.parse(text) }; } catch { return { available: true, provider: "Google Gemini", data: { answer: text } }; }
}

export function safeSatellite(farmId: string, period = "30d") {
  return { farmId, period, ...unavailable("Satellite/Earth Engine"), ndvi: { current: 0.61, previous: 0.7, change: -0.09 }, zones: [{ zone: "A", ndvi: 0.71, status: "healthy", color: "#3D7A52" }, { zone: "B", ndvi: 0.52, status: "moderate", color: "#C9A000" }, { zone: "C", ndvi: 0.34, status: "stressed", color: "#C04A3A" }], weatherPoints: [], riskPoints: [], note: "Connect Earth Engine credentials and a satellite data adapter for live observations." };
}
function safeWeather() { return { available: false, provider: "Weather data adapter", forecast: [], risk: "unknown", note: "Configure a weather provider to enable live forecasts." }; }

async function ownsFarm(userId: number, farmId: string) {
  const db = await getDb();
  if (!db) { const row = memory.farms.get(farmId); return row?.userId === userId ? row : undefined; }
  return getOwnedFarm(farmId, userId);
}

export function registerAgriNexusRoutes(app: Express) {
  app.get(`${api}/health`, (_req, res) => res.json({ ok: true, service: "agrinexus-api", ai: Boolean(process.env.GOOGLE_GEMINI_API_KEY), timestamp: Date.now() }));
  app.get(`${api}/demo/:mode`, (req, res) => {
    const demos: Record<string, any> = {
      farmer: { title: "Crop Intelligence Report", items: [{ label: "Crop", value: "Wheat", color: "#3D7A52" }, { label: "Health Score", value: "68/100", color: "#E67E22" }, { label: "Disease Risk", value: "Medium – Rust Probable", color: "#E67E22" }, { label: "Weather Risk", value: "Low", color: "#3D7A52" }, { label: "NDVI Trend", value: "Declining (–0.09)", color: "#C04A3A" }], recommendation: "Inspect field within 24 hours. Confirm observations with a local agronomist before treatment." },
      field: { title: "Satellite Farm Analysis", items: [{ label: "NDVI Average", value: "0.61 – Moderate", color: "#C9A000" }, { label: "Stressed Area", value: "1.1 ha (Zone SW)", color: "#D4551A" }, { label: "Water Stress", value: "Detected – 7-day deficit", color: "#E67E22" }, { label: "Soil Moisture", value: "Provider unavailable", color: "#E67E22" }, { label: "Climate Risk", value: "Awaiting live provider", color: "#3D7A52" }], recommendation: "Connect satellite, weather, and soil providers for live field observations. Do not act on placeholder measurements." },
      policy: { title: "Regional Intelligence Brief", items: [{ label: "Farms Monitored", value: "Aggregated data", color: "#3D7A52" }, { label: "Advisory Adoption", value: "Provider unavailable", color: "#4A8FAA" }, { label: "High-Risk Farms", value: "Provider unavailable", color: "#D4551A" }, { label: "Top Risk Factor", value: "Awaiting analytics", color: "#E67E22" }, { label: "NDVI Trend", value: "Awaiting satellite data", color: "#3D7A52" }], recommendation: "Policy analytics will use anonymized, aggregated records once approved data sources are connected." },
    };
    const response = demos[req.params.mode];
    if (!response) return res.status(404).json({ error: "Unknown demo mode" });
    res.json({ mode: req.params.mode, response, source: "AgriNexus backend demo contract" });
  });

  app.post(`${api}/profiles`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = farmerSchema.parse(req.body); const row = { id: id("farmer"), userId: user.id, ...input, createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(farmerProfiles).values(row); else memory.profiles.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/profiles/me`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); const row = db ? (await db.select().from(farmerProfiles).where(eq(farmerProfiles.userId, user.id)).limit(1))[0] : Array.from(memory.profiles.values()).find(v => v.userId === user.id); res.json(row ?? null); });

  app.post(`${api}/farms`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = farmSchema.parse(req.body); const row = { id: id("farm"), userId: user.id, ...input, createdAt: new Date(), updatedAt: new Date() }; const db = await getDb(); if (db) await db.insert(farms).values(row); else memory.farms.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/farms`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); res.json(db ? await db.select().from(farms).where(eq(farms.userId, user.id)).orderBy(desc(farms.createdAt)) : Array.from(memory.farms.values()).filter(v => v.userId === user.id)); });
  app.get(`${api}/farms/:farmId`, async (req, res) => { const user = await auth(req, res); if (!user) return; const farm = await ownsFarm(user.id, req.params.farmId); if (!farm) return res.status(404).json({ error: "Farm not found" }); res.json(farm); });

  app.post(`${api}/crops`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = z.object({ farmId: z.string(), name: z.string().min(1).max(80), variety: z.string().max(120).optional(), season: z.string().max(40).optional(), plantedAt: z.coerce.date().optional() }).parse(req.body); if (!(await ownsFarm(user.id, input.farmId))) return res.status(403).json({ error: "You do not own this farm" }); const row = { id: id("crop"), userId: user.id, ...input, createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(crops).values(row); else memory.fields.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/farms/:farmId/crops`, async (req, res) => { const user = await auth(req, res); if (!user) return; if (!(await ownsFarm(user.id, req.params.farmId))) return res.status(404).json({ error: "Farm not found" }); const db = await getDb(); res.json(db ? await db.select().from(crops).where(eq(crops.farmId, req.params.farmId)) : []); });

  app.post(`${api}/fields`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = fieldSchema.parse(req.body); if (!(await ownsFarm(user.id, input.farmId))) return res.status(403).json({ error: "You do not own this farm" }); const row = { id: id("field"), userId: user.id, ...input, createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(fields).values(row); else memory.fields.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/farms/:farmId/fields`, async (req, res) => { const user = await auth(req, res); if (!user) return; if (!(await ownsFarm(user.id, req.params.farmId))) return res.status(404).json({ error: "Farm not found" }); const db = await getDb(); res.json(db ? await db.select().from(fields).where(eq(fields.farmId, req.params.farmId)) : Array.from(memory.fields.values()).filter(v => v.farmId === req.params.farmId)); });

  app.post(`${api}/chat`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = chatSchema.parse(req.body); let context = "No saved farm context."; if (input.farmId) { const farm = await ownsFarm(user.id, input.farmId); if (!farm) return res.status(403).json({ error: "You do not own this farm" }); context = JSON.stringify(farm); } const result = await gemini(`You are a cautious agricultural advisor for India. Answer in ${input.language}. Use the saved context below. Return JSON with answer, actions (array), urgency (low|medium|high), evidence, and disclaimer. Never prescribe regulated chemicals or claim diagnosis. Context: ${context}. Crop: ${input.crop || "unknown"}. Farmer question: ${input.message}`); res.json({ ...result, conversationId: id("conversation") }); } catch (e) { res.status(502).json({ error: "AI advisory unavailable", detail: e instanceof Error ? e.message : "provider error", fallback: true }); } });

  app.post(`${api}/crop/assess`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = photoSchema.parse(req.body); if (input.farmId && !(await ownsFarm(user.id, input.farmId))) return res.status(403).json({ error: "You do not own this farm" }); const result = await gemini(`Assess this ${input.crop} crop image conservatively. Return JSON with healthScore (0-100), findings (array of label, confidence, evidence), nextActions (array), urgency (low|medium|high), and disclaimer. Treat output as observational triage, not a diagnosis. Respond in ${input.language}.`, input.imageBase64 ? { data: input.imageBase64, mimeType: input.mimeType } : undefined); const row = { id: id("assessment"), userId: user.id, farmId: input.farmId ?? null, crop: input.crop, imageUrl: input.imageUrl ?? null, result: JSON.stringify(result), createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(cropAssessments).values(row); else memory.assessments.set(row.id, row); res.status(201).json({ assessmentId: row.id, crop: input.crop, ...result, disclaimer: "AI-generated observations require confirmation by a qualified agronomist or local agricultural officer." }); } catch (e) { jsonError(res, e); } });

  app.post(`${api}/farms/:farmId/analyze`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = analysisSchema.parse({ ...req.body, farmId: req.params.farmId }); if (!(await ownsFarm(user.id, input.farmId))) return res.status(404).json({ error: "Farm not found" }); const satellite = input.includeSatellite ? safeSatellite(input.farmId) : null; const weather = input.includeWeather ? safeWeather() : null; const result = await gemini(`Return JSON for a farm analysis with cropHealth (0-100), ndvi, ndviTrend, waterStress, climateRisk, stressedAreaHectares, evidence, recommendation, urgency, and disclaimer. Use this non-live evidence: ${JSON.stringify({ satellite, weather, soil: input.includeSoil ? unavailable("Soil data") : null })}. Crop: ${input.crop}. Do not invent provider measurements.`); const analysis = { analysisId: id("analysis"), status: "completed", crop: input.crop, ...result, satellite, weather }; res.json(analysis); } catch (e) { res.status(502).json({ error: "Farm analysis unavailable", fallback: true, satellite: safeSatellite(req.params.farmId), weather: safeWeather(), detail: e instanceof Error ? e.message : "provider error" }); } });
  app.get(`${api}/farms/:farmId/satellite`, async (req, res) => { const user = await auth(req, res); if (!user) return; if (!(await ownsFarm(user.id, req.params.farmId))) return res.status(404).json({ error: "Farm not found" }); res.json(safeSatellite(req.params.farmId, String(req.query.period || "30d"))); });

  app.post(`${api}/advisories`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const body = z.object({ farmId: z.string(), crop: z.string(), goal: z.enum(["sowing", "irrigation", "risk", "general"]).default("general"), language: z.string().default("English") }).parse(req.body); const farm = await ownsFarm(user.id, body.farmId); if (!farm) return res.status(403).json({ error: "You do not own this farm" }); const weather = await getWeather(farm.latitude, farm.longitude); const publicData = await getPublicAgricultureData(body.crop, "India"); const context = { farm, weather, publicData }; const result = await gemini(`Create actionable ${body.goal} guidance for an Indian farmer. Return JSON with title, actions, timing, risks, confidence, and disclaimer. Use only this saved farm context and provider data, explicitly label unavailable sources, and do not invent measurements. Language: ${body.language}. Crop: ${body.crop}. Context: ${JSON.stringify(context)}`); const row = { id: id("advisory"), userId: user.id, farmId: body.farmId, crop: body.crop, goal: body.goal, result: JSON.stringify(result), createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(advisories).values(row); else memory.advisories.set(row.id, row); res.status(201).json({ advisoryId: row.id, ...result, context }); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/advisories`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); res.json(db ? await db.select().from(advisories).where(eq(advisories.userId, user.id)).orderBy(desc(advisories.createdAt)) : Array.from(memory.advisories.values()).filter(v => v.userId === user.id)); });

  app.post(`${api}/alerts`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = z.object({ farmId: z.string().optional(), title: z.string().min(1).max(160), message: z.string().min(1).max(2000), priority: z.enum(["low", "medium", "high"]).default("medium") }).parse(req.body); if (input.farmId && !(await ownsFarm(user.id, input.farmId))) return res.status(403).json({ error: "You do not own this farm" }); const row = { id: id("alert"), userId: user.id, ...input, createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(alerts).values(row); else memory.alerts.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.get(`${api}/alerts`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); res.json(db ? await db.select().from(alerts).where(eq(alerts.userId, user.id)).orderBy(desc(alerts.createdAt)) : Array.from(memory.alerts.values()).filter(v => v.userId === user.id)); });
  app.get(`${api}/nudges`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); res.json(db ? await db.select().from(nudges).where(eq(nudges.userId, user.id)).orderBy(desc(nudges.createdAt)) : Array.from(memory.nudges.values()).filter(v => v.userId === user.id)); });
  app.post(`${api}/nudges`, async (req, res) => { const user = await auth(req, res); if (!user) return; try { const input = z.object({ farmId: z.string().optional(), title: z.string().min(1).max(160), message: z.string().min(1).max(2000), priority: z.enum(["low", "medium", "high"]).default("medium"), dueAt: z.coerce.date().optional() }).parse(req.body); if (input.farmId && !(await ownsFarm(user.id, input.farmId))) return res.status(403).json({ error: "You do not own this farm" }); const row = { id: id("nudge"), userId: user.id, ...input, status: "pending" as const, createdAt: new Date() }; const db = await getDb(); if (db) await db.insert(nudges).values(row); else memory.nudges.set(row.id, row); res.status(201).json(row); } catch (e) { jsonError(res, e); } });
  app.post(`${api}/nudges/:nudgeId/complete`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); if (db) await db.update(nudges).set({ status: "completed", completedAt: new Date() }).where(and(eq(nudges.id, req.params.nudgeId), eq(nudges.userId, user.id))); else { const row = memory.nudges.get(req.params.nudgeId); if (row?.userId === user.id) { row.status = "completed"; row.completedAt = new Date(); } } res.json({ success: true }); });
  app.post(`${api}/nudges/:nudgeId/dismiss`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); if (db) await db.update(nudges).set({ status: "dismissed" }).where(and(eq(nudges.id, req.params.nudgeId), eq(nudges.userId, user.id))); else { const row = memory.nudges.get(req.params.nudgeId); if (row?.userId === user.id) row.status = "dismissed"; } res.json({ success: true }); });
  app.post(`${api}/alerts/:alertId/read`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); if (db) await db.update(alerts).set({ readAt: new Date() }).where(and(eq(alerts.id, req.params.alertId), eq(alerts.userId, user.id))); else { const row = memory.alerts.get(req.params.alertId); if (row?.userId === user.id) row.readAt = new Date(); } res.json({ success: true }); });
  app.get(`${api}/dashboard`, async (req, res) => { const user = await auth(req, res); if (!user) return; const db = await getDb(); const ownedFarms = db ? await db.select().from(farms).where(eq(farms.userId, user.id)) : Array.from(memory.farms.values()).filter(v => v.userId === user.id); const userAlerts = db ? await db.select().from(alerts).where(eq(alerts.userId, user.id)) : Array.from(memory.alerts.values()).filter(v => v.userId === user.id); res.json({ stats: { farms: ownedFarms.length, unreadAlerts: userAlerts.filter(a => !a.readAt).length, monitoredFields: 0, advisoryAdoption: null }, farms: ownedFarms, alerts: userAlerts, privacy: "Personal dashboard data is scoped to the authenticated account." }); });
}
